<a href="https://colab.research.google.com/github/Tomokki/data-analysis-basic-kadai/blob/main/kadai_003.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Step1.
### NumPyをインポートするコードを記述する

In [1]:
# numpyの読み込み
import numpy as np


# Step2.
### AとBの行列を格納する多次元配列のコードを記述する

In [9]:
A =np.array([[0,1],[2,3],[4,5]])
A


array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
B =np.array([[0,1,2,3],[4,5,6,7]])
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

# Step3.
### 行列の積の計算をするコードを記述する
# Step4.
### Step3.の計算結果を表示するコードを記述する

In [10]:
A =np.array([[0,1],[2,3],[4,5]])
B =np.array([[0,1,2,3],[4,5,6,7]])

np.dot(A, B)


array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

# Step5.
### 行列の要素の最大値を求めるコードを記述する

In [11]:
np.dot(A, B).max()

47